### ISSUE TITLE
当前阶梯剩余额度貌似有问题

### ISSUE THREAD

**Issue by CrazyMouse** [georgezhao2010/bj_sgcc_energy#1]
![image](https://user-images.githubusercontent.com/1176862/129674821-bfc85013-f6a1-4bb7-a93f-fb34f4aca42f.png)

**Comment by georgezhao2010** [comment]
打开该插件的Debug日志输出
```
logger:
  default: warn
  logs:
    custom_components.bj_sgcc_energy: debug
```
然后把插件相关的Data开头的那条JSON日志发上来，户号请提前做处理
